model_path : "meta-llama/Llama-2-7B-chat-hf"

data_path:
  generation : "datasets/generate_dataset.json"
  test : "datasets/test_dataset.json"

save_vector_path : "vectors/"

steering_vector_path : "vectors/steering_vector.pt"

target_layer : 13